# Generated by Django 3.0.3 on 2020-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('studentNames', models.CharField(max_length=80)),
                ('genres', models.CharField(max_length=128)),
                ('studentIds', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=128)),
                ('build', models.FileField(upload_to='games/')),
                ('hasBeenApproved', models.BooleanField(default=False)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
