# Generated by Django 3.0.4 on 2020-03-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('studentNames', models.CharField(max_length=80)),
                ('studentIds', models.CharField(max_length=60)),
                ('build', models.FileField(upload_to='')),
                ('hasBeenApproved', models.BooleanField(default=False)),
            ],
        ),
    ]
