# Generated by Django 3.0.3 on 2020-04-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='studentNames',
            new_name='developers',
        ),
    ]
